package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_closure//closure:defs.bzl", "web_library")

web_library(
    name = "app_templates_web",
    path = "/templates",
    srcs = [
        "home.bui",
        "home2.bui"
    ],
)
