package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_closure//closure:defs.bzl", "web_library")

web_library(
    name = "app_images_web",
    path = "/images",
    srcs = [
        "logo.png"
    ],
)
