package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_closure//closure:defs.bzl", "web_library")

web_library(
    name = "core_components_templates",
    path = "/templates/core/components",
    srcs = [
        "core/components/drawer.bui"
    ],
)
