workspace(name = "badu_product_sl")

local_repository(
    name = "com_google_j2cl",
    path = "../tools/j2cl",
)

load("@com_google_j2cl//build_defs:repository.bzl", "load_j2cl_repo_deps")
load_j2cl_repo_deps()

load("@com_google_j2cl//build_defs:rules.bzl", "setup_j2cl_workspace")
setup_j2cl_workspace()

new_local_repository(
    name = "projectlibs",
    path = "../libs",
    build_file = "../libs/BUILD.libs",
)
