workspace(name = "badu_product_sl")

# Load j2cl repository
# load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
# http_archive(
#     name = "com_google_j2cl",
#     strip_prefix = "j2cl-master",
#     url = "https://github.com/google/j2cl/archive/master.zip",
# )

local_repository(
    name = "com_google_j2cl",
    path = "../tools/j2cl",
)

load("@com_google_j2cl//build_defs:repository.bzl", "load_j2cl_repo_deps")
load_j2cl_repo_deps()

load("@com_google_j2cl//build_defs:rules.bzl", "setup_j2cl_workspace")
setup_j2cl_workspace()

new_local_repository(
    name = "projectlibs",
    path = "../libs",
    build_file = "../libs/BUILD.libs",
)
